// src/constants.js

export const demoStudents = [
  {
    id: 0,
    name: 'Avinash Pandey',
    phone: '9319765934',
    email: 'avinash12291pandey@gmail.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'Essex University',
    course: 'MBA',
    status: 'Active Students',
  },
  {
    id: 1,
    name: 'Anshu Kumar',
    phone: '2378327432',
    email: 'anshu.kumar@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'Essex',
    course: 'MSc Finance',
    status: 'Under Review',
  },
  {
    id: 2,
    name: 'Avi Sharma',
    phone: '9999999999',
    email: 'avi.sharma@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'King’s College London',
    course: 'BSc Computer Science',
    status: 'Action Required',
  },
  {
    id: 3,
    name: 'Aisha Khan',
    phone: '7123456789',
    email: 'aisha.khan@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'Keele University',
    course: 'BA Psychology',
    status: 'Approved',
  },
  {
    id: 4,
    name: 'Rahul Verma',
    phone: '8234567123',
    email: 'rahul.verma@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'University of Manchester',
    course: 'MEng Mechanical',
    status: 'Rejected',
  },
  {
    id: 5,
    name: 'Priya Singh',
    phone: '9456123780',
    email: 'priya.singh@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'University of Leeds',
    course: 'MSc Data Science',
    status: 'Active Students',
  },
  {
    id: 6,
    name: 'John Doe',
    phone: '7012345678',
    email: 'john.doe@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'Loughborough University',
    course: 'BEng Electrical',
    status: 'Under Review',
  },
  {
    id: 7,
    name: 'Jane Smith',
    phone: '7023456789',
    email: 'jane.smith@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'University of Birmingham',
    course: 'MA English',
    status: 'Action Required',
  },
  {
    id: 8,
    name: 'Michael Brown',
    phone: '7034567890',
    email: 'michael.brown@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'University of Bristol',
    course: 'MSc Chemistry',
    status: 'Approved',
  },
  {
    id: 9,
    name: 'Emily Davis',
    phone: '7045678901',
    email: 'emily.davis@example.com',
    country: 'United Kingdom',
    state: 'UK',
    university: 'University of Edinburgh',
    course: 'PhD Physics',
    status: 'Active Students',
  },
];

export const statuses = [
  { title: 'Active Students',   baseBg: '#E3F2FD', selBg: '#BBDEFB', border: '#1976d2' },
  { title: 'Under Review',      baseBg: '#FFFDE7', selBg: '#FFF9C4', border: '#FFD700' },
  { title: 'Action Required',   baseBg: '#FFEBEE', selBg: '#FFCDD2', border: '#FF8A00' },
  { title: 'Approved',          baseBg: '#E8F5E9', selBg: '#C8E6C9', border: '#2ECC71' },
  { title: 'Rejected',          baseBg: '#FCE4EC', selBg: '#F8BBD0', border: '#E74C3C' },
];
